-- Schema para pacientes-service
-- Tabla de pacientes

CREATE TABLE IF NOT EXISTS pacientes (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cedula VARCHAR(50) NOT NULL UNIQUE,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    telefono VARCHAR(20),
    direccion VARCHAR(255),
    email VARCHAR(100),
    fecha_nacimiento DATE
);

CREATE INDEX IF NOT EXISTS idx_pacientes_cedula ON pacientes(cedula);
CREATE INDEX IF NOT EXISTS idx_pacientes_nombre ON pacientes(nombre);
